[package]
name = "ptr_iter"
description = "Iterators to simplify working with pointers."
repository = "https://github.com/Lokathor/ptr_iter"
version = "0.1.1"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
